server:
  port: 10260

spring:
  application:
    name: mq-tx-account
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/monkey?useSSL=false&rewriteBatchedStatements=true
    username: root
    password: Admin888
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.100
    port: 6379
    password: Admin888


# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:10000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
  mapper-locations: org/monkey/mqtx/account/mapper/AccountMapper.xml
