server:
  port: 10071

spring:
  application:
    name: dist-order
  datasource:
    url: jdbc:mysql://192.168.71.128:3306/dist-order?useSSL=false&rewriteBatchedStatements=true
    username: root
    password: Admin888
    driver-class-name: com.mysql.cj.jdbc.Driver


# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka

# mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
  mapper-locations: org/monkey/dist/order/mapper/OrderDetailMapper.xml
