server:
  port: 10270

spring:
  application:
    name: mq-tx-agent


# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:10000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
