server:
  port: 10270

spring:
  application:
    name: mq-tx-agent
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: monkey
    password: 123456
    virtual-host: monkey_vhost
    publisher-returns: true             # 开启回退模式 消息从 exchange 到 queue 投递失败有一个 returnCallback 退回模式。
    publisher-confirm-type: correlated  # 开启发布确认 消息从 producer 到 rabbitmq broker有一个 confirmCallback 确认模式。
    listener:
      simple:
        prefetch: 5
        acknowledge-mode: manual # 开启手动ack

# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:10000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
