server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
#        - id: auth
#          uri: http://localhost:10010
#          predicates:
#            - Path=/auth/**

        - id: user
          uri: http://localhost:10020
          predicates:
            - Path=/user/**

        - id: dist-order
          uri: http://localhost:10071
          predicates:
            - Path=/dist/order/**

        - id: dist-store
          uri: http://localhost:10072
          predicates:
            - Path=/dist/store/**


# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
