server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          #uri: http://192.168.1.100:10020
          uri: lb://user
          predicates:
            - Path=/user/**

        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**

        - id: rabbitmq-receiver
          uri: lb://rabbitmq-receiver
          predicates:
            - Path=/rabbitmq/receiver/**

        - id: rabbitmq-sender
          uri: lb://rabbitmq-sender
          predicates:
            - Path=/rabbitmq/sender/**

        - id: mq-tx-account
          uri: lb://mq-tx-account
          predicates:
            - Path=/mqtx/account/**

# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:10000/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
